// type= 0 |input
// type= 1 |select
// list已选择的筛选数据
// lists筛选数据源
// EditDisabled //编辑时不可见,
// isShow 表格列是否显示
let COLUMNS = [
	// {
	// 	label: '归属线路',
	// 	width: '200',
	// 	parent: '0',
	// 	id: '0-1',
	// 	prop: 'BelongLineName',
	// 	sortable: false,
	// 	required: false,
	// 	disabled: true,
	// 	isShow: true,
	// 	EditDisabled: true,
	// 	type: 0,
	// 	list: [],
	// 	lists: [],
	// 	filterShow: false,
	// },
	// {
	// 	label: '归属单位',
	// 	width: '200',
	// 	parent: '0',
	// 	id: '0-2',
	// 	prop: 'BelongCompanyName',
	// 	isShow: true,
	// 	EditDisabled: true,
	// 	sortable: false,
	// 	required: false,
	// 	disabled: true,
	// 	type: 0,
	// 	list: [],
	// 	lists: [],
	// 	filterShow: false,
	// },
	//#region  必填项
	{
		label: '人员基本信息',
		width: '200',
		prop: '',
		id: '1',
		pid: true,
		parent: null,
		sortable: false,
		// disableCheck: true,
		required: true,

		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '基本信息',
		width: '200',
		prop: '',
		id: '1-1',
		parent: '1',
		pid: true,
		sortable: false,
		// disableCheck: true,
		required: true,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '身份证',
		width: '200',
		prop: 'IDCard',
		sortable: true,
		id: '1-1-1',
		parent: '1-1',
		// disableCheck: true,
		required: true,
		disabled: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '姓名',
		width: '200',
		id: '1-1-2',
		parent: '1-1',
		prop: 'UserName',
		sortable: true,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '联系电话',
		width: '200',
		id: '1-1-3',
		parent: '1-1',
		prop: 'PhoneNumber',
		sortable: true,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '人员类别',
		width: '200',
		id: '1-1-4',
		parent: '1-1',
		prop: 'UserType',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['管理人员', '作业人员', '后勤（含保安）'],

		list: [],
		lists: [],
		filterShow: false,
	},

	{
		label: '性别',
		width: '200',
		id: '1-1-5',
		parent: '1-1',
		prop: 'Sex',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['男', '女'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '在场状态',
		width: '200',
		id: '1-1-6',
		parent: '1-1',
		prop: 'WorkStatus',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['在场', '退场'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '民族',
		width: '200',
		id: '1-1-7',
		parent: '1-1',
		prop: 'Nation',
		sortable: false,
		required: true,
		type: 1,
		defaultData: [
			'汉',
			'蒙古',
			'回',
			'藏',
			'维吾尔',
			'苗',
			'彝',
			'壮',
			'布依',
			'朝鲜',
			'满',
			'侗',
			'瑶',
			'白',
			'土家',
			'哈尼',
			'哈萨克',
			'傣',
			'黎',
			'傈僳',
			'佤',
			'畲',
			'高',
			'拉祜',
			'水',
			'东乡',
			'纳西',
			'景颇',
			'柯尔克孜',
			'土',
			'达斡尔',
			'仫佬',
			'羌',
			'布朗',
			'撒拉',
			'毛难',
			'仡佬',
			'锡伯',
			'阿昌',
			'普米',
			'塔吉克',
			'怒',
			'乌孜别克',
			'俄罗斯',
			'鄂温克',
			'崩龙',
			'保安',
			'裕固',
			'京',
			'塔塔尔',
			'独龙',
			'鄂伦春',
			'赫哲',
			'门巴',
			'珞巴',
			'基诺',
			'其他',
		],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '出生日期',
		width: '200',
		id: '1-1-8',
		parent: '1-1',
		prop: 'Birthday',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '籍贯',
		width: '200',
		id: '1-1-9',
		parent: '1-1',
		prop: 'Native',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '户口所在地',
		width: '200',
		id: '1-1-10',
		parent: '1-1',
		prop: 'Location',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '组织信息',
		width: '200',
		prop: 'IDCard',
		id: '1-2',
		pid: true,
		parent: '1',
		sortable: false,
		// disableCheck: true,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '线路',
		width: '200',
		id: '1-2-1',
		parent: '1-2',
		prop: 'LineName',
		sortable: false,
		required: true,
		type: 1,
		defaultData: [
			'八号线北延段',
			'二十二号线后通段',
			'二十一号线',
			'广佛线',
			'六号线二期',
			'六号线首期',
			'七号线二期',
			'七号线西延段',
			'三号线',
			'三号线东延段',
			'十八号线后通段',
			'十二号线',
			'十号线',
			'十三号线二期',
			'十四号线二期',
			'十一号线',
			'天河路至体育东路人行地道',
			'五号线东延段',
			'广花城际',
			'知识城',
			'新广从',
			'芳白城际',
			'其他',
		],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '分部',
		width: '200',
		id: '1-2-2',
		parent: '1-2',
		prop: 'DivisionName',
		sortable: false,
		required: true,
		type: 1,
		defaultData: [
			'/',
			'总包部',
			'1分部',
			'2分部',
			'3分部',
			'4分部',
			'5分部',
			'6分部',
			'7分部',
			'8分部',
			'9分部',
			'10分部',
			'11分部',
			'12分部',
			'13分部',
			'14分部',
			'15分部',
			'华隧分部',
			'水电二局分部',
			'小标段',
			'广建分部',
			'机电1分部',
			'机电2分部',
			'机电3分部',
			'其他',
		],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '工区',
		width: '200',
		id: '1-2-3',
		parent: '1-2',
		prop: 'WorkSection',
		sortable: false,
		required: true,
		type: 1,
		defaultData: [
			'/',
			'1工区',
			'2工区',
			'3工区',
			'4工区',
			'5工区',
			'6工区',
			'7工区',
			'8工区',
			'9工区',
			'10工区',
			'其他',
		],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '工点',
		width: '200',
		id: '1-2-4',
		parent: '1-2',
		prop: 'BuildingName',
		sortable: false,
		required: true,
		type: 1,
		defaultData: [
			'/',
			'E21#井至纪念堂区间',
			'E31#盾构井至花城广场北区间',
			'E41#至棠下区间',
			'E42#至车陂区间',
			'白鹅潭站（土建）',
			'白鹅潭站后竖井',
			'白鹅潭站站前明挖段（土建）',
			'白马岗站（土建）',
			'白马岗至马场区间',
			'白云文化广场站（土建）',
			'保盈大道站（土建）',
			'保盈大道至广州开发区区间',
			'北滘公园站（机电）',
			'滨江东路站（土建）',
			'彩虹桥站（机电）',
			'彩虹桥站（土建）',
			'彩虹桥至E21#井区间',
			'彩虹桥至纪念堂区间E21#盾构井',
			'彩虹桥至流花路区间',
			'彩虹桥至中山八区间',
			'仓边路站（土建）',
			'仓边路站过街通道',
			'槎头车辆段',
			'槎头车辆段出入段线（土建）',
			'槎头站（土建）',
			'朝阳站（土建）',
			'朝阳至庆丰区间',
			'朝阳至庆丰区间中间风井',
			'车陂站（土建）',
			'车陂至E43#井区间盾构吊出井',
			'陈头岗-西三区间',
			'赤岗站（土建）',
			'赤沙车辆段',
			'赤沙车辆段出入段线（土建）',
			'赤沙滘站（土建）',
			'赤沙滘至琶洲区间',
			'赤沙站（土建）',
			'赤沙至赤岗区间',
			'赤沙至赤沙滘区间',
			'创意园站（土建）',
			'创意园至马务区间',
			'大干围站（土建）',
			'大干围至东沙区间',
			'大金钟站（土建）',
			'大金钟至广园新村区间',
			'大沙东站（土建）',
			'大沙东至姬堂区间',
			'大沙东至姬堂中间风井',
			'大塘站（土建）',
			'大塘至石榴岗区间',
			'大学城北站（土建）',
			'大学城北至大学城南区间',
			'大学城北至大学城南区间3#中间风井',
			'大学城南停车场',
			'大学城南停车场出入场线（土建）',
			'大学城南站(土建)',
			'大学城南至深井区间',
			'大学城南至深井区间中间风井',
			'东湖-滨江东路区间',
			'东湖站（土建）',
			'东湖站至署前路站区间',
			'东湖站至署前路站区间中间风井（土建）',
			'东湖至烈士陵园区间',
			'东沙工业园站（土建）',
			'东沙站（土建）',
			'东晓南站（土建）',
			'鹅掌坦站3号口',
			'二沙岛站（土建）',
			'二沙岛至东湖区间',
			'二沙岛至岭南广场区间',
			'番番区间盾构井',
			'番番区间盾构井至番禺客运站区间',
			'番禺广场至番番区间盾构井区间',
			'番禺客运站（土建）',
			'番禺客运站至广州新城西区间中间风井',
			'番禺客运站至广州新城西站',
			'芳村大道东站（土建）',
			'芳村站（土建）',
			'芳村至芳村大道东区间',
			'岗贝站（土建）',
			'岗贝至乐嘉路区间',
			'高塘石站IV号口（机电）',
			'工业大道站（土建）',
			'工业大道站-大干围站区间',
			'官洲站（土建）',
			'官洲至大学城北区间',
			'广钢新城车辆段',
			'广钢新城停车场出入段线',
			'广钢新城站（土建）',
			'广钢新城至西塱区间',
			'广钢新城至西塱区间盾构吊出井',
			'广园新村站（土建）',
			'广园新村至恒福路区间',
			'广园新村至恒福路区间2#中间风井',
			'广园新村至梓元岗区间',
			'广州大道中站（土建）',
			'广州东换乘节点',
			'广州东站（土建）',
			'广州东站至沙河区间',
			'广州东站至沙河区间中间风井',
			'广州火车站（土建）',
			'广州火车站至流花路区间',
			'广州开发区站（土建）',
			'广州开发区至黄埔客运港区间',
			'广州新城停车场出入场线',
			'广州新城西站（土建）',
			'海傍站（土建）',
			'鹤洞东站（土建）',
			'鹤洞东至南石路区间',
			'鹤洞东至沙涌区间',
			'鹤南站（土建）',
			'恒福路站（土建）',
			'洪圣沙站（土建）',
			'洪圣沙至裕丰围区间',
			'花城广场北站（土建）',
			'华景路站（土建）',
			'华景路至华师区间',
			'华景路至华师区间1#竖井',
			'华景路至华师区间2#竖井',
			'华景路至华师区间3#竖井',
			'华景路至华师区间新增竖井',
			'华师站（土建）',
			'华师站A口',
			'华师至天河东区间',
			'黄埔客运港站（土建）',
			'凰岗停车场',
			'凰岗停车场出入场线',
			'凰岗停车场盖体',
			'凰岗站（土建）',
			'凰岗至槎头区间',
			'姬堂停车场',
			'姬堂停车场出入场线',
			'姬堂站（土建）',
			'姬堂至加庄区间',
			'纪念堂站（土建）',
			'加庄站（土建）',
			'加庄至科丰路区间',
			'嘉禾望岗至彭边区间',
			'建设六马路至农林下路区间',
			'江泰路站（土建）',
			'江泰路至五凤区间',
			'金光大道站（土建）',
			'金光大道至广州新城西区间',
			'金光大道至海傍区间',
			'景云路站（土建）',
			'菊树站A口',
			'菊树站B口',
			'聚龙站（土建）',
			'聚龙至棠溪区间',
			'柯木塱站Ⅲ号口（机电）',
			'科丰路站（土建）',
			'科丰路至萝岗区间',
			'科丰路至萝岗区间中间风井',
			'乐嘉路站（土建）',
			'乐嘉路至广州火车站区间中间风井',
			'里横路站（土建）',
			'里横路至槎头区间',
			'里横路至槎头区间1#中间风井',
			'烈士陵园站（土建）',
			'岭南广场站（土建）',
			'岭南广场至赤岗区间竖井',
			'流花路站（土建）',
			'仑头站（土建）',
			'仑头至官洲区间',
			'罗冲围站（土建）',
			'萝岗站（土建）',
			'萝岗至水西区间',
			'马场站（土建）',
			'马场至石牌南区间',
			'马务站（土建）',
			'梅东路站（土建）',
			'梅东路至E31#盾构井区间',
			'梅东路至花城广场区间E31#盾构井',
			'美的站（机电）',
			'庙头路站（土建）',
			'鸣泉主变电所',
			'南航新村站（土建）',
			'南航新村至棠溪区间',
			'南石路站（土建）',
			'农林下路站（土建）',
			'农林下路至梅东路区间',
			'琶洲站（土建）',
			'琶洲至员村区间',
			'彭边站（土建）',
			'彭边至鹤南区间',
			'庆丰站（土建）',
			'庆丰至凰岗区间',
			'人行地道',
			'如意坊站（土建）',
			'如意坊至石围塘区间',
			'沙河站（土建）',
			'沙河至田心村区间',
			'沙涌站（土建）',
			'沙涌至芳村大道东区间',
			'上涌公园站（土建）',
			'上涌公园至逸景路区间',
			'深井站（土建）',
			'深井至长洲区间',
			'神舟路站Ⅲ号口',
			'神舟路站Ⅳ号口',
			'神舟路站Ⅴ号口',
			'石榴岗站（土建）',
			'石榴岗至赤沙滘区间',
			'石榴岗至赤沙滘区间中间风井',
			'石牌南站（土建）',
			'石潭站1号口',
			'石围塘站（土建）',
			'石围塘至芳村区间',
			'双岗停车场',
			'双岗停车场出入段线',
			'双岗站（土建）',
			'双岗至庙头区间',
			'双岗至庙头区间竖井',
			'双岗至庙头区间中间风井',
			'水西北站（土建）',
			'水西北站后折返线',
			'水西站（土建）',
			'水西站Ⅳ号口',
			'水西至水西北区间',
			'寺右新马路站（土建）',
			'松溪站（土建）',
			'棠下站（土建）',
			'棠下至车陂区间E42#盾构井',
			'天河东站（土建）',
			'天河东至广州东站区间',
			'天河东至广州东站区间中间风井',
			'天河公园站（土建）',
			'天河公园至E41#区间',
			'天河公园至白马岗区间',
			'天河公园至华景路区间',
			'天河公园至棠下区间E41#盾构井',
			'天河路站（土建）',
			'天河路至广州大道中区间',
			'田心村至云台花园区间',
			'文冲至双岗区间',
			'文冲至双岗区间竖井',
			'五凤站（土建）',
			'西场站（土建）',
			'西场至彩虹桥区间',
			'西村站（机电）',
			'西村站（土建）',
			'西朗站（土建）',
			'西塱站（土建）',
			'西塱站站后折返线',
			'西塱站站前配线段',
			'西三站（土建）',
			'西洲站（土建）',
			'西洲至槎头区间',
			'西洲至松溪区间',
			'夏南车辆段部分零星土建工程',
			'夏园站（土建）',
			'夏园至保盈大道区间',
			'冼村站（土建）',
			'冼广中间风井',
			'小金钟站（土建）',
			'新市墟站（土建）',
			'浔峰岗站（土建）',
			'浔峰岗至里横路区间',
			'燕岗站（土建）',
			'燕岗至江泰路区间',
			'一德路站Ia号口（土建）',
			'一德路站Ib号口（土建）',
			'逸景路站（土建）',
			'鱼珠车辆段改造',
			'鱼珠停车场',
			'鱼珠停车场出入场线',
			'裕丰围站（土建）',
			'裕丰围至大沙东区间',
			'原厦滘车辆段改造',
			'云台花园站（土建）',
			'云台花园至大金钟区间',
			'云台花园至大金钟区间1#竖井',
			'云台花园至大金钟区间2#竖井',
			'云溪公园站（土建）',
			'长洲站（土建）',
			'长洲至洪圣沙区间',
			'植物园站IV号出入口加装垂直电梯井',
			'中大南门站（土建）',
			'中山八站（土建）',
			'珠村站（土建）',
			'珠村至E44#井区间',
			'珠村至E44#井区间盾构始发井',
			'梓元岗站（土建）',
		],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '工点所在行政区',
		width: '200',
		id: '1-2-5',
		parent: '1-2',
		prop: 'WorkAreaZone',
		sortable: false,
		required: true,
		type: 1,
		defaultData: [
			'天河区',
			'越秀区',
			'荔湾区',
			'海珠区',
			'番禺区',
			'白云区',
			'花都区',
			'增城区',
			'从化区',
			'南沙区',
			'黄埔区',
			'佛山',
		],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '单位',
		width: '200',
		id: '1-2-6',
		parent: '1-2',
		prop: 'CompanyName',
		sortable: false,
		required: true,
		type: 1,
		defaultData: [
			'其他',
			'三号线东延段总承包',
			'五号线东延段总承包部',
			'七号线二期总承包部',
			'十号线总承包部',
			'十一号线总承包部',
			'十二号线总承包部',
			'十三号线二期总承包部',
			'十四号线二期总包部',
			'十八/二十二号线总承包部',
			'芳白城际总承包部',
			'广花城际总承包部',
			'中铁二局',
			'中铁建大桥局',
			'中铁一局',
			'广东华隧',
			'水电二局',
			'中国铁建电气化局',
			'中铁二十二局',
			'中铁二十五局',
			'中铁十八局',
			'中铁十九局',
			'中铁十四局',
			'中铁十一局',
			'中铁八局',
			'中铁北京局',
			'中铁电气化局',
			'中铁广州局',
			'中铁建工',
			'中铁三局',
			'中铁十局',
			'中铁四局',
			'中铁隧道局',
			'中铁武汉电气化局',
			'中铁一局',
			'广东华隧',
			'宏润建设集团',
			'中铁二局',
			'中铁二十四局',
			'中铁广州局',
			'中铁十八局',
			'中铁十一局',
			'中铁武汉电气化局',
			'中铁一局',
			'广州盾建与广州市政联合体',
			'广州建筑',
			'中铁五局',
			'中国铁建电气化局',
			'中铁二十二局',
			'中铁二十五局',
			'中铁建大桥局',
			'中铁十八局',
			'中铁十二局',
			'中铁十九局',
			'中铁十四局',
			'中铁十五局',
			'中铁十一局',
			'广东华隧',
			'中交二公司',
			'中交广州公司',
			'中交三航局',
			'中交四航局',
			'中交隧道局',
			'中交一航局',
			'中铁一局',
			'北京城建',
			'中铁二十局',
			'中铁二十五局',
			'中铁二十一局',
			'中铁建大桥局',
			'中铁十八局',
			'中铁十九局',
			'中铁十六局',
			'中铁十一局',
			'中铁八局',
			'中铁北京局',
			'中铁电气化局',
			'中铁二局',
			'中铁广州局',
			'中铁建工',
			'中铁六局',
			'中铁七局',
			'中铁三局',
			'中铁上海局',
			'中铁十局',
			'中铁四局',
			'中铁隧道局',
			'中铁五局',
			'中铁一局',
			'广东华隧',
			'水电二局',
			'中铁十九局',
			'广州建筑',
			'中铁电气化局',
			'中铁二局',
			'中铁广州局',
			'中铁建工',
			'中铁三局',
			'中铁上海局',
			'中铁隧道局',
			'中铁五局',
			'中铁一局',
			'北京建工集团',
			'北京建工土木工程',
			'中铁三局',
			'广州市市政工程监理有限公司',
			'四川铁科建设监理有限公司',
			'乌鲁木齐铁建工程咨询有限公司',
			'北京中铁诚业工程建设监理有限公司',
			'广东重工建设监理有限公司',
			'广州轨道交通建设监理有限公司',
			'天津路安工程咨询有限公司',
			'中铁二院(成都)咨询监理有限责任公司',
			'北京铁城建设监理有限责任公司',
			'广东建科建设咨询有限公司',
			'广州轨道交通建设监理有限公司',
			'广州建筑工程监理有限公司',
			'北京铁城建设监理有限责任公司',
			'北京现代通号工程咨询有限公司',
			'广东工程建设监理有限公司',
			'广东重工建设监理有限公司',
			'广州市城市建设工程监理公司',
			'广州珠江工程建设监理有限公司',
			'广州轨道交通建设监理有限公司',
			'北京中铁诚业工程建设监理有限公司',
			'广东铁路建设监理有限公司',
			'广东重工建设监理有限公司',
			'四川铁科建设监理有限公司',
			'天津路安工程咨询有限公司',
			'乌鲁木齐铁建工程咨询有限公司',
			'北京铁城建设监理有限责任公司',
			'广东工程建设监理有限公司',
			'广州市城市建设工程监理公司',
			'广州珠江工程建设监理有限公司',
			'深圳市中弘策工程顾问有限公司',
			'铁四院(湖北)工程监理咨询有限公司',
			'北京中铁诚业工程建设监理有限公司',
			'天津路安工程咨询有限公司',
			'中国水利水电建设工程咨询中南有限公司',
			'中铁华铁工程设计集团有限公司',
			'北京中铁诚业工程建设监理有限公司',
			'广州轨道交通建设监理有限公司',
			'广州市城市建设工程监理公司',
			'西安铁一院工程咨询监理有限责任公司',
			'中煤中原（天津）建设监理咨询有限公司',
			'中铁二院(成都)咨询监理有限责任公司',
			'中铁济南工程建设监理有限公司',
			'广东建科建设咨询有限公司',
			'广东重工建设监理有限公司',
			'广州轨道交通建设监理有限公司',
			'铁四院(湖北)工程监理咨询有限公司',
			'乌鲁木齐铁建工程咨询有限公司',
			'中国水利水电建设工程咨询中南有限公司',
			'广东重工建设监理有限公司',
			'广州地铁设计研究院股份有限公司（原广州地铁设计研究院有限公司）',
			'中铁第六勘察设计院集团有限公司（原中铁隧道勘测设计院有限公司）',
			'北京城建勘测设计研究院有限责任公司',
			'广东省地质建设工程勘察院',
			'招商局重庆交通科研设计院有限公司',
			'广东省工程勘察院',
			'广东省重工建筑设计院有限公司',
			'中铁第六勘察设计院集团有限公司（原中铁隧道勘测设计院有限公司）',
			'北京城建勘测设计研究院有限责任公司',
			'广东省重工建筑设计院有限公司',
			'广州地铁设计研究院股份有限公司（原广州地铁设计研究院有限公司）',
			'中国有色金属长沙勘察设计研究院有限公司',
			'广东省工程勘察院',
			'广东省重工建筑设计院有限公司',
			'中铁第六勘察设计院集团有限公司（原中铁隧道勘测设计院有限公司）',
			'北京城建勘测设计研究院有限责任公司',
			'广东省重工建筑设计院有限公司',
			'广州地铁设计研究院股份有限公司（原广州地铁设计研究院有限公司）',
			'中铁第六勘察设计院集团有限公司（原中铁隧道勘测设计院有限公司）',
			'北京城建勘测设计研究院有限责任公司',
			'广东省建科建筑设计院有限公司',
			'广东省重工建筑设计院有限公司',
			'广州地铁设计研究院股份有限公司（原广州地铁设计研究院有限公司）',
			'广州地铁设计研究院股份有限公司（原广州地铁设计研究院有限公司）',
			'广东建准检测技术有限公司',
			'广东省建设工程质量安全检测总站有限公司',
			'广州继善建筑技术有限公司',
			'广州建设工程质量安全检测中心有限公司',
			'广州市建设工程质量安全检测中心',
			'广州市盛通建设工程质量检测有限公司',
			'广州继善建筑技术有限公司',
			'广州建设工程质量安全检测中心有限公司',
			'广州市建筑材料工业研究所有限公司',
			'广州市盛通建设工程质量检测有限公司',
			'广东省建设工程质量安全检测总站有限公司',
			'广东合众路桥科技股份有限公司',
			'广东省建设工程质量安全检测总站有限公司',
			'广州地铁设计研究院股份有限公司',
			'广州建设工程质量安全检测中心有限公司',
			'广州市建设工程质量安全检测中心',
			'广东建准检测技术有限公司',
			'广州继善建筑技术有限公司',
			'广州市建筑材料工业研究所有限公司',
			'广州市盛通建设工程质量检测有限公司',
			'华测检测股份有限公司',
			'广东建准检测技术有限公司',
			'广州继善建筑技术有限公司',
			'广州建设工程质量安全检测中心有限公司',
			'广州市建筑材料工业研究所有限公司',
			'广州市盛通建设工程质量检测有限公司',
			'广东省建设工程质量安全检测总站有限公司',
			'广州建设工程质量安全检测中心有限公司',
			'广州市建设工程质量安全检测中心',
			'广州市建筑材料工业研究所有限公司',
			'广州市盛通建设工程质量检测有限公司',
			'广东建准检测技术有限公司',
			'广州继善建筑技术有限公司',
			'广州市建筑材料工业研究所有限公司',
			'广州市盛通建设工程质量检测有限公司',
			'华测检测股份有限公司',
			'广东省建设工程质量安全检测总站有限公司',
			'广州市建设工程质量安全检测中心',
			'广州市盛通建设工程质量检测有限公司',
			'广东省建设工程质量安全检测总站有限公司',
			'广州建设工程质量安全检测中心有限公司',
			'广州市建设工程质量安全检测中心',
			'广州市建筑材料工业研究所有限公司',
			'广州市盛通建设工程质量检测有限公司',
			'广东省建设工程质量安全检测总站有限公司',
			'广州建设工程质量安全检测中心有限公司',
			'广州市建筑材料工业研究所有限公司',
			'广州市盛通建设工程质量检测有限公司',
			'广东合众路桥科技股份有限公司',
			'广东省建设工程质量安全检测总站有限公司',
			'广州地铁设计研究院股份有限公司',
			'广州建设工程质量安全检测中心有限公司',
			'广州市建设工程质量安全检测中心',
		],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '岗位',
		width: '200',
		id: '1-2-7',
		parent: '1-2',
		prop: 'Position',
		sortable: false,
		required: true,
		type: 1,
		defaultData: [
			'/',
			'总经理',
			'常务副总经理',
			'党工委书记',
			'纪工委书记',
			'总顾问',
			'党工委副书记',
			'副总经理',
			'总经济师',
			'总会计师',
			'设备总监',
			'安全总监',
			'总工程师',
			'副总工程师',
			'部长',
			'副部长',
			'部员',
			'段长',
			'驻地代表',
			'分部经理',
			'分部副经理（盾构）',
			'分部副经理',
			'党工委书记',
			'党工委副书记',
			'总经济师',
			'总会计师',
			'总工程师',
			'安全总监',
			'副总工程师',
			'副总工程师（盾构）',
			'部长',
			'部长（盾构）',
			'副部长',
			'部员',
			'分部调度员',
			'安全监督官',
			'工区经理',
			'工区书记',
			'常务副经理',
			'副经理',
			'盾构经理/盾构队长',
			'技术主任/盾构总工',
			'盾构副经理/机长/生产副队长',
			'设备副队长/设备主管',
			'后勤主管',
			'安全总监',
			'总工程师',
			'副总工程师',
			'部长',
			'副部长',
			'部员',
			'施工员',
			'安全员',
			'技术员',
			'质检员',
			'材料员/配件管理员',
			'资料员',
			'测量员',
			'生产调度员',
			'搅拌站站长',
			'泥水站负责人',
			'土建工程师',
			'机电工程师',
			'刀具工程师',
			'地面工班长',
			'井下工班长',
			'测量主管/测量班长',
			'维修班长',
			'班组长',
			'总监',
			'副总监',
			'区域负责人',
			'区域助理',
			'模块牵头人',
			'项目经理',
			'项目助理',
			'总监理工程师',
			'副总监',
			'总监代表',
			'安全主任',
			'联络员',
			'专业监理工程师',
			'安全监理工程师',
			'投资监理',
			'其他',
			'工区副经理',
		],
		list: [],
		lists: [],
		filterShow: false,
	},

	{
		label: '工种',
		width: '200',
		id: '1-2-8',
		parent: '1-2',
		prop: 'WorkName',
		sortable: false,
		required: true,
		type: 1,
		defaultData: [
			'/',
			'混凝土工',
			'钢筋工',
			'模板工',
			'砌筑工（建筑瓦工、瓦工）',
			'测量放线工（测量工、工程测量员）',
			'防水工',
			'架子工',
			'掌子工',
			'盾构司机',
			'同步注浆工',
			'二次注浆工',
			'管片拼装手',
			'电瓶车司机',
			'管片修补工',
			'螺杆工',
			'双轨梁工',
			'双轨梁辅助工',
			'跟机电工',
			'地面电工',
			'盾构机维修工',
			'搅拌机司机',
			'随车员',
			'汽车式起重机司机',
			'门式起重机司机',
			'桥式起重机司机',
			'塔式起重机司机',
			'物料提升机司机',
			'升降机司机',
			'桩机司机',
			'旋挖钻司机',
			'压路机司机',
			'平地机司机',
			'渣土运输车司机',
			'推土、铲运机司机',
			'挖掘机司机',
			'桩工（打桩工）',
			'叉车司机',
			'工程机械修理工',
			'机械设备安装工',
			'建筑起重机械安装拆卸工',
			'起重信号工（起重信号司索工）',
			'电梯安装维修工',
			'爆破工',
			'建筑电工',
			'电焊工（焊工）',
			'通风工',
			'附着升降脚手架安装拆卸工',
			'高处作业吊篮操作工',
			'高处作业吊篮安装拆卸工',
			'管线工',
			'变电安装工',
			'弱电工',
			'中央空调系统运行操作员',
			'智能楼宇管理员',
			'接触网工',
			'仪表安装调试工',
			'空调安装调试工',
			'司泵工',
			'金属工',
			'幕墙安装工（建筑幕墙安装工）',
			'建筑门窗安装工',
			'幕墙制作工',
			'构件装配工',
			'构件制作工',
			'预埋工',
			'安装钳工',
			'室内成套设施安装工',
			'安装铆工',
			'消防安装工',
			'安装起重工（起重工、起重装卸机械操作工）',
			'电气设备安装调试工',
			'泵站操作工',
			'水暖工',
			'油漆工',
			'抹灰工',
			'木工',
			'镶贴工',
			'涂裱工',
			'装饰装修木工',
			'防腐保温工',
			'杂工',
			'拌合机上料',
			'充电工',
			'试验工',
			'工区副经理',
		],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '是否特殊工种',
		width: '200',
		id: '1-2-9',
		parent: '1-2',
		prop: 'IsSpecialWork',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['/', '是', '否'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '劳务队类型',
		width: '200',
		id: '1-2-10',
		parent: '1-2',
		prop: 'LaborType',
		sortable: false,
		required: true,
		type: 1,
		defaultData: [
			'/',
			'临建施工队',
			'地连墙施工队',
			'土方开挖施工队',
			'主体结构施工队',
			'盾构施工队',
			'降水施工队',
			'支撑施工队',
			'三轴搅拌桩施工队',
			'箱梁铺设轨道加固施工队',
			'综合接地施工队',
			'防水队伍',
			'杂工施工队',
			'场段施工队',
			'暗挖施工队',
			'机电安装施工队',
			'区间机电安装施工队',
			'弱电安装施工队',
			'区间弱电安装施工队',
			'整体道床施工队',
			'无缝线路施工队',
			'供电安装施工队',
			'区间供电安装施工队',
			'区间测量队',
			'人防防护施工队',
			'民用通信安装施工队',
			'其他',
		],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '班组类型',
		width: '200',
		id: '1-2-11',
		parent: '1-2',
		prop: 'TeamType',
		sortable: false,
		required: true,
		type: 1,
		defaultData: [
			'/',
			'钢筋班',
			'混凝土班',
			'模板工班',
			'砌筑班',
			'架子班',
			'装修班',
			'杂工班',
			'司索工班',
			'地面班组',
			'掘进班组',
			'维修班组',
			'测量班',
			'后勤',
			'土方开挖和外运',
			'给排水及消防班组',
			'通风与空调班组',
			'低压配点班组',
			'高压细水雾班组',
			'气体灭火器班组',
			'智能建筑（ACS）班组',
			'智能建筑（FAS）班组',
			'智能建筑（BAS）班组',
			'弱电班组',
			'信号班组',
			'临建施工班组',
			'砌筑装修班组',
			'接触网班组',
			'疏散平台班组',
			'环网电缆班组',
			'外电源班组',
			'主变电班组',
			'人防防护班组',
			'民用通信班组',
			'其他',
		],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '广州地铁累计工作年限（年）',
		width: '200',
		id: '1-2-12',
		parent: '1-2',
		prop: 'WorkYears',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '广州地铁工作简历',
		width: '200',
		id: '1-2-13',
		parent: '1-2',
		prop: 'WorkExperience',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},

	{
		label: '居住信息',
		width: '200',
		id: '1-3',
		parent: '1',
		pid: true,
		prop: 'WorkExperience',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '定居省市',
		width: '200',
		id: '1-3-1',
		parent: '1-3',
		prop: 'SettleLocation',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '定居详细地址',
		width: '200',
		id: '1-3-2',
		parent: '1-3',
		prop: 'SettleAddress',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},

	{
		label: '广州市暂住区',
		width: '200',
		id: '1-3-3',
		parent: '1-3',
		prop: 'StayLocation',
		sortable: false,
		required: true,
		type: 1,
		defaultData: [
			'天河区',
			'越秀区',
			'荔湾区',
			'海珠区',
			'番禺区',
			'白云区',
			'花都区',
			'增城区',
			'从化区',
			'南沙区',
			'黄埔区',
			'佛山',
		],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '广州市居住地住址详细地址',
		width: '200',
		id: '1-3-4',
		parent: '1-3',
		prop: 'StayAddress',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '是否在场外暂住',
		width: '200',
		id: '1-3-5',
		parent: '1-3',
		prop: 'IsStayOutside',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['是', '否'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '住宿方式',
		width: '200',
		id: '1-3-6',
		parent: '1-3',
		prop: 'AccommodationMode',
		sortable: false,
		required: true,

		type: 1,
		defaultData: ['场外住宿', '场内住宿'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '场外住宿地类型(场内住宿选无)',
		width: '200',
		id: '1-3-7',
		parent: '1-3',
		prop: 'StayOutsideType',
		sortable: false,
		required: true,
		type: 1,
		defaultData: [
			'亲戚暂住-城中村',
			'亲戚暂住-小区',
			'租房-城中村',
			'租房-小区',
			'其他',
			'无',
		],
		list: [],
		lists: [],
		filterShow: false,
	},
	// todo
	{
		label: '是否工地内集中居住',
		width: '200',
		id: '1-3-8',
		parent: '1-3',
		prop: 'IsSiteCentered',
		sortable: false,
		requied: true,
		type: 1,
		defaultData: ['是', '否'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '是否工地外集中居住',
		width: '200',
		id: '1-3-9',
		parent: '1-3',
		prop: 'IsOutsideCentered',
		sortable: false,
		requied: true,
		type: 1,
		defaultData: ['是', '否'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '是否工地外分散居住',
		width: '200',
		id: '1-3-10',
		parent: '1-3',
		prop: 'IsSiteDecentralized',
		sortable: false,
		requied: true,
		type: 1,
		defaultData: ['是', '否'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '防疫信息',
		width: '200',
		id: '2',
		pid: true,
		parent: null,
		prop: 'ArriveTime',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '来穗情况',
		width: '200',
		pid: true,
		id: '2-1',
		parent: '2',
		prop: 'ArriveTime',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '最近一次来穗时间',
		width: '200',
		id: '2-1-1',
		parent: '2-1',
		prop: 'ArriveTime',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},

	{
		label: '是否为春节后来穗人员',
		width: '200',
		id: '2-1-2',
		parent: '2-1',
		prop: 'IsAfterSpring',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['是', '否'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '从何地来穗',
		width: '200',
		id: '2-1-3',
		parent: '2-1',
		prop: 'WhereForm',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '是否省外来穗',
		width: '200',
		id: '2-1-4',
		parent: '2-1',
		// 待修改
		prop: 'IsOutsideProvince',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['是', '否'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '来穗交通方式',
		width: '200',
		id: '2-1-5',
		parent: '2-1',
		prop: 'Transportation',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['飞机', '火车', '高铁', '私家车', '网约车', '其他'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '交通工具编号',
		width: '200',
		id: '2-1-6',
		parent: '2-1',
		prop: 'TransportationNumber',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '项目部报道情况',
		width: '200',
		id: '2-2',
		pid: true,
		parent: '2',
		prop: '',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '是否已进入项目报道',
		width: '200',
		id: '2-2-1',
		parent: '2-2',
		prop: 'EntryExitMode',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['进场', '退场'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '报道时间',
		width: '200',
		id: '2-2-2',
		parent: '2-2',
		prop: 'EntryExitDate',
		sortable: true,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '旅居情况',
		width: '200',
		id: '2-3',
		pid: true,
		parent: '2',
		prop: 'In14DaysMainHistory',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '14天主要旅居史',
		width: '200',
		id: '2-3-1',
		parent: '2-3',
		prop: 'In14DaysMainHistory',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},

	{
		label: '高中风险地区或本土病例活动区域旅居史情况',
		width: '200',
		id: '2-3-2',
		parent: '2-3',
		prop: 'InHighSchoolRiskAreasHistory',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['有', '无'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '高中风险地区、或本土病例所在市旅居史情况',
		width: '200',
		parent: '2-3',
		id: '2-3-3',
		prop: 'HighRiskAreaOrNativeHistory',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['有', '无'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '高中风险地区或本土病所在省份旅居史情况',
		width: '200',
		parent: '2-3',
		id: '2-3-4',
		prop: 'HighRiskAreaOrNativeHistory',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['有', '无'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '高中风险地区、所在市、所在省旅居具体情况',
		width: '200',
		parent: '2-3',
		id: '2-3-5',
		prop: 'HighRiskAreaCityProvinceSituation',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '健康自查',
		width: '200',
		parent: '2',
		id: '2-4',
		pid: true,
		prop: 'HasPersonalHealthSituation',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label:
			'返穗时个人健康情况（是否有干咳、乏力、嗅味觉减退、鼻塞、流涕、咽痛、结膜炎、肌痛、腹泻等不适症状）',
		width: '400',
		parent: '2-4',
		id: '2-4-1',
		prop: 'HasPersonalHealthSituation',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['是', '否'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '健康码颜色',
		width: '200',
		parent: '2-4',
		id: '2-4-2',
		prop: 'HealthCodeColor',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['绿色', '黄色', '红色'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '行程码是否带*',
		width: '200',
		parent: '2-4',
		id: '2-4-3',
		prop: 'IsTheTripRisk',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['是', '否'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '抵穗核酸情况',
		width: '200',
		parent: '2',
		id: '2-5',
		pid: true,
		prop: 'IsTheTripRisk',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '抵穗后48小时内是否完成核酸检测',
		width: '200',
		parent: '2-5',
		id: '2-5-1',
		prop: 'IsNatIn48Hours',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['是', '否'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '核酸检测时间',
		width: '200',
		parent: '2-5',
		id: '2-5-2',
		prop: 'NatDate',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '核酸检测结果',
		width: '200',
		parent: '2-5',
		id: '2-5-3',
		prop: 'NatResult',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['阴性', '阳性'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '抵穗后是否完成“三天两检”',
		width: '200',
		parent: '2-5',
		id: '2-5-4',
		prop: 'IsTwoThreeDays',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['是', '否'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '核酸检测时间（第一次）',
		width: '200',
		parent: '2-5',
		id: '2-5-5',
		prop: 'FirstNatDate',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '核酸检测结果（第一次）',
		width: '200',
		parent: '2-5',
		id: '2-5-6',
		prop: 'FirstNatResult',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['阴性', '阳性'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '核酸检测时间（第二次）',
		width: '200',
		parent: '2-5',
		id: '2-5-7',
		prop: 'SecondNatDate',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '核酸检测结果（第二次）',
		width: '200',
		parent: '2-5',
		id: '2-5-8',
		prop: 'SecondNatResult',
		sortable: false,
		required: true,

		type: 1,
		defaultData: ['阴性', '阳性'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '抵穗健康监测情况',
		width: '200',
		parent: '2',
		id: '2-6',
		pid: true,
		prop: 'SecondNatResult',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '抵穗后是否落实14天健康监测',
		width: '200',
		parent: '2-6',
		id: '2-6-1',
		prop: 'Is14DayHealthMonitoring',
		sortable: false,
		required: true,

		type: 1,
		defaultData: ['是', '否'],
		list: [],
		lists: [],
		filterShow: false,
	},

	{
		label: '健康监测地点类型',
		width: '200',
		parent: '2-6',
		id: '2-6-2',
		prop: 'HealthMonitoringType',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['项目部独立区', '酒店'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '健康监测开始时间',
		width: '200',
		parent: '2-6',
		id: '2-6-3',
		prop: 'HealthMonitoringStartDate',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '健康监测结束时间',
		width: '200',
		parent: '2-6',
		id: '2-6-4',
		prop: 'HealthMonitoringEndDate',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '健康监测期间健康情况',
		width: '200',
		parent: '2-6',
		id: '2-6-5',
		prop: 'HealthMonitoringResult',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['正常', '异常'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '疫苗接种情况',
		width: '200',
		parent: '2',
		id: '2-7',
		pid: true,
		prop: 'HealthMonitoringResult',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '是否接种第一针',
		width: '200',
		parent: '2-7',
		id: '2-7-1',
		// 待修改
		prop: 'IsFirstVaccination',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['是', '否'],
		list: [],
		lists: [],
		filterShow: false,
	},

	{
		label: '第一针疫苗接种时间',
		width: '200',
		parent: '2-7',
		id: '2-7-2',
		prop: 'FirstVaccinationDate',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '是否接种第二针',
		width: '200',
		parent: '2-7',
		id: '2-7-3',
		// 待修改
		prop: 'IsSecondVaccination',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['是', '否'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '第二针疫苗接种时间',
		width: '200',
		parent: '2-7',
		id: '2-7-4',
		prop: 'SecondVaccinationDate',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '满足“加强针”时间',
		width: '200',
		parent: '2-7',
		id: '2-7-5',
		prop: 'IsMeetTheNeedleTime',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '是否满足“加强针”针条件',
		width: '200',
		parent: '2-7',
		id: '2-7-6',

		prop: 'IsMeetTheNeedleConditions',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['是', '否'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '是否接种加强针',
		width: '200',
		parent: '2-7',
		id: '2-7-7',
		// 待修改
		prop: 'IsTheNeedle',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['是', '否'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '“加强针”疫苗接种时间',
		width: '200',
		parent: '2-7',
		id: '2-7-8',
		prop: 'TheNeedleDate',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '一人一档情况',
		width: '200',
		parent: '2',
		id: '2-8',
		pid: true,
		prop: '',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '是否参加至少一次防疫政策和技术培训',
		width: '200',
		parent: '2-8',
		id: '2-8-1',
		prop: 'IsLeastOnceEpidemicTraining',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['是', '否'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '是否建立或更新“一人一档”',
		width: '200',
		parent: '2-8',
		id: '2-8-2',
		prop: 'IsEstablishArchive',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['是', '否'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '是否报项目负责人书面同意',
		width: '200',
		parent: '2-8',
		id: '2-8-3',
		prop: 'IsProjectLeaderAgrees',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['是', '否'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '是否按要求落实核酸“一周一检”',
		width: '200',
		parent: '2-8',
		id: '2-8-4',
		prop: 'IsCheckOnceWeek',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['是', '否'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '最近核酸情况',
		width: '200',
		parent: '2',
		pid: true,
		id: '2-9',
		prop: 'Nearly14DaysNatDate',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '近14天核酸检测时间',
		width: '200',
		parent: '2-9',
		id: '2-9-1',
		prop: 'Nearly14DaysNatDate',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '近14天核酸检测结果',
		width: '200',
		parent: '2-9',
		id: '2-9-2',
		prop: 'Nearly14DaysNatResult',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['阴性', '阳性'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '最近一次核酸检测时间',
		width: '200',
		parent: '2-9',
		id: '2-9-3',
		prop: 'LastNatDate',
		sortable: false,
		required: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '最近一次核酸检测结果',
		width: '200',
		parent: '2-9',
		id: '2-9-4',
		prop: 'LastNatResult',
		sortable: false,
		required: true,
		type: 1,
		defaultData: ['阴性', '阳性'],
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '补充信息',
		width: '200',
		parent: null,
		id: '3',
		pid: true,
		prop: 'CreatorName',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '个人基础信息补充',
		width: '200',
		parent: '3',
		id: '3-1',
		pid: true,
		prop: 'CreatorName',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '上报人',
		width: '200',
		parent: '3-1',
		id: '3-1-1',
		prop: 'CreatorName',
		sortable: true,
		required: false,
		disabled: true,
		EditDisabled: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '上报日期',
		width: '200',
		parent: '3-1',
		id: '3-1-2',
		prop: 'CreateDate',
		sortable: true,
		required: false,
		EditDisabled: true,
		disabled: true,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},

	//#endregion  必填项
	//#region  非必填字段
	{
		label: '政治面貌',
		width: '200',
		parent: '3-1',
		id: '3-1-3',
		prop: 'PoliticalStatus',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '教育程度',
		width: '200',
		parent: '3-1',
		id: '3-1-4',
		prop: 'EduLevelNum',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '学位',
		width: '200',
		parent: '3-1',
		id: '3-1-5',
		prop: 'DegreeNum',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '特长',
		width: '200',
		parent: '3-1',
		id: '3-1-6',
		prop: 'Specialty',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '电子邮箱',
		width: '200',
		parent: '3-1',
		id: '3-1-7',
		prop: 'Email',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '婚姻状况',
		width: '200',
		parent: '3-1',
		id: '3-1-8',
		prop: 'MaritalStatus',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '是否有重大',
		width: '200',
		parent: '3-1',
		id: '3-1-9',
		prop: 'HasBadMedicalHistory',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '社保号',
		width: '200',
		parent: '3-1',
		id: '3-1-10',
		prop: 'SecurityCode',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},

	{
		label: '工作信息',
		width: '200',
		parent: '3',
		id: '3-2',
		pid: true,
		prop: 'WorkDate',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '开始工作日期',
		width: '200',
		parent: '3-2',
		id: '3-2-1',
		prop: 'WorkDate',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '是否加入工会',
		width: '200',
		parent: '3-2',
		id: '3-2-2',
		prop: 'IsJoinedUnion',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '加入工会时间',
		width: '200',
		parent: '3-2',
		id: '3-2-3',
		prop: 'JoinedUnionDate',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '用工形式',
		width: '200',
		parent: '3-2',
		id: '3-2-4',
		prop: 'EmploymentForm',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '加入项目的时间',
		width: '200',
		parent: '3-2',
		id: '3-2-5',
		prop: 'JoinedProjectDate',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '薪酬基础信息',
		width: '200',
		parent: '3',
		id: '3-3',
		pid: true,
		prop: 'PayRollBankCardNumber',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '工资卡账号',
		width: '200',
		parent: '3-3',
		id: '3-3-1',
		prop: 'PayRollBankCardNumber',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '开户银行',
		width: '200',
		parent: '3-3',
		id: '3-3-2',
		prop: 'PayRollBankName',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '发放工资总行名称',
		width: '200',
		parent: '3-3',
		id: '3-3-3',
		prop: 'PayRollTopBankName',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '工资卡银行联号',
		width: '200',
		parent: '3-3',
		id: '3-3-4',
		prop: 'BankLinkNumber',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '个人证书信息',
		width: '200',
		parent: '3',
		id: '3-4',
		pid: true,
		prop: 'CredentialName',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '证书名称',
		width: '200',
		parent: '3-4',
		id: '3-4-1',
		prop: 'CredentialName',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '证书种类',
		width: '200',
		parent: '3-4',
		id: '3-4-2',
		prop: 'CredentialType',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '证书类型',
		width: '200',
		parent: '3-4',
		id: '3-4-3',
		prop: 'CertificationType',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '证书等级',
		width: '200',
		parent: '3-4',
		id: '3-4-4',
		prop: 'CredentialLevel',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '证书编号',
		width: '200',
		parent: '3-4',
		id: '3-4-5',
		prop: 'CredentialNumber',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '资质证书状态',
		width: '200',
		parent: '3-4',
		id: '3-4-6',
		prop: 'CertificationStatus',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '认定部门',
		width: '200',
		parent: '3-4',
		id: '3-4-7',
		prop: 'CredentialDepartment',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '第一次发证时间',
		width: '200',
		parent: '3-4',
		id: '3-4-8',
		prop: 'FirstIssuingDate',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '证书有效时间(起)',
		width: '200',
		parent: '3-4',
		id: '3-4-9',
		prop: 'CertificateEffectiveStartDate',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '证书有效时间(止)',
		width: '200',
		parent: '3-4',
		id: '3-4-10',
		prop: 'CertificateEffectiveEndDate',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '作业人员补充信息（作业人员填写）',
		width: '200',
		parent: null,
		id: '4',
		pid: true,
		prop: 'WorkAge',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '劳务信息',
		width: '200',
		parent: '4',
		id: '4-1',
		pid: true,
		prop: 'WorkAge',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '工龄',
		width: '200',
		parent: '4-1',
		id: '4-1-1',
		prop: 'WorkAge',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '在岗状态',
		width: '200',
		parent: '4-1',
		id: '4-1-2',
		prop: 'PostStatus',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '所属劳务单位名称',
		width: '200',
		parent: '4-1',
		id: '4-1-3',
		prop: 'LaborCompanyName',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '负责人',
		width: '200',
		parent: '4-1',
		id: '4-1-4',
		prop: 'Charges',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '负责人联系方式',
		width: '200',
		parent: '4-1',
		id: '4-1-5',
		prop: 'ChargesPhoneNumber',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '劳务队长',
		width: '200',
		parent: '4-1',
		id: '4-1-6',
		prop: 'Captain',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '劳务队长联系方式',
		width: '200',
		parent: '4-1',
		id: '4-1-7',
		prop: 'CaptainPhoneNumber',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '班组名称',
		width: '200',
		parent: '4-1',
		id: '4-1-8',
		prop: 'TeamName',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '班组长姓名',
		width: '200',
		parent: '4-1',
		id: '4-1-9',
		prop: 'TeamLeaderName',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '班组长联系方式',
		width: '200',
		parent: '4-1',
		id: '4-1-10',
		prop: 'TeamLeaderPhoneNumber',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '考核等级',
		width: '200',
		parent: '4-1',
		id: '4-1-11',
		prop: 'AssessmentLevel',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '班组进场时间',
		width: '200',
		parent: '4-1',
		id: '4-1-12',
		prop: 'TeamEntryTime',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '班组退场时间',
		width: '200',
		parent: '4-1',
		id: '4-1-13',
		prop: 'TeamExitTime',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '特殊工种信息',
		width: '200',
		parent: '4',
		id: '4-2',
		pid: true,
		prop: 'TeamExitTime',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},

	{
		label: '特殊工种证书号码',
		width: '200',
		parent: '4-2',
		id: '4-2-1',
		prop: 'SpecialNumber',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '技能等级',
		width: '200',
		parent: '4-2',
		id: '4-2-2',
		prop: 'SkillGrading',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: ' 特殊工种证书发证单位',
		width: '200',
		parent: '4-2',
		id: '4-2-3',
		prop: 'SpecialDepartment',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '特种作业证证件号',
		width: '200',
		parent: '4-2',
		id: '4-2-4',
		prop: 'SpecialCode',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: '特种作业证生效日期',
		width: '200',
		parent: '4-2',
		id: '4-2-5',
		prop: 'SpecialStartDate',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: ' 特种作业证失效日期',
		width: '200',
		parent: '4-2',
		id: '4-2-6',
		prop: 'SpecialEndDate',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: ' 特种作业证失效日期',
		width: '200',
		parent: '4-2',
		id: '4-2-7',
		prop: 'SpecialEndDate',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: ' 安全教育信息',
		width: '200',
		parent: '4',
		id: '4-3',
		pid: true,
		prop: 'IsSafetyEdu',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: ' 是否参加安全教育',
		width: '200',
		parent: '4-3',
		id: '4-3-1',
		prop: 'IsSafetyEdu',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: ' 一级安全教育时间',
		width: '200',
		parent: '4-3',
		id: '4-3-2',
		prop: 'FirstSafeEduDate',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: ' 二级安全教育时间',
		width: '200',
		parent: '4-3',
		id: '4-3-3',
		prop: 'SecondSafeEduDate',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: ' 三级安全教育时间',
		width: '200',
		parent: '4-3',
		id: '4-3-4',
		prop: 'ThirdSafeEduDate',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: ' 安全技术交底时间',
		width: '200',
		parent: '4-3',
		id: '4-3-5',
		prop: 'SafeTeachDiscloseDate',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: ' 一对一面谈时间',
		width: '200',
		parent: '4-3',
		id: '4-3-6',
		prop: 'OneOnOneDate',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: ' 体检信息',
		width: '200',
		parent: '4',
		id: '4-4',
		pid: true,
		prop: 'OneOnOneDate',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: ' 血型',
		width: '200',
		parent: '4-4',
		id: '4-4-1',
		prop: 'BloodType',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: ' 体检结果',
		width: '200',
		parent: '4-4',
		id: '4-4-2',
		prop: 'MedicalResult',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: ' 体检日期',
		width: '200',
		parent: '4-4',
		id: '4-4-3',
		prop: 'MedicalDate',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: ' 体检报告时间',
		width: '200',
		parent: '4-4',
		id: '4-4-4',
		prop: 'MedicalReportDate',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: ' 合同信息',
		width: '200',
		parent: '4',
		id: '4-5',
		pid: true,
		prop: 'HasBuyInjuryInsurance',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: ' 是否购买工伤保险',
		width: '200',
		parent: '4-5',
		id: '4-5-1',
		prop: 'HasBuyInjuryInsurance',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: ' 是否购买商业性意外险',
		width: '200',
		parent: '4-5',
		id: '4-5-2',
		prop: 'HasBuyCommercialInsurance',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: ' 是否有劳动合同',
		width: '200',
		parent: '4-5',
		id: '4-5-3',
		prop: 'HasContract',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: ' 劳动合同编号',
		width: '200',
		parent: '4-5',
		id: '4-5-4',
		prop: 'ContractCode',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: ' 合同期限类型',
		width: '200',
		parent: '4-5',
		id: '4-5-5',
		prop: 'ContractPeriodType',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: ' 结算方式',
		width: '200',
		parent: '4-5',
		id: '4-5-6',
		prop: 'Settlement',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: ' 单价',
		width: '200',
		parent: '4-5',
		id: '4-5-7',
		prop: 'UnitPrice',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: ' 计量单位',
		width: '200',
		parent: '4-5',
		id: '4-5-8',
		prop: 'MeasureUnit',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: ' 合同开始时间',
		width: '200',
		parent: '4-5',
		id: '4-5-9',
		prop: 'ContractStartDate',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},
	{
		label: ' 合同失效日期',
		width: '200',
		parent: '4-5',
		id: '4-5-10',
		prop: 'ContractEndDate',
		sortable: false,
		required: false,
		type: 0,
		list: [],
		lists: [],
		filterShow: false,
	},

	//#endregion 非必填字段
];
module.exports = {
	COLUMNS: COLUMNS,
};
